In [1]:
from google.colab import files, drive
files.upload()

Saving test_data (2).csv to test_data (2) (1).csv
Saving train_data (2).csv to train_data (2) (1).csv

{'test_data (2) (1).csv': b'id,name,make,model,year,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain\r\n803,2023 Dodge Durango Pursuit,Dodge,Durango,2023,16V MPFI OHV,8,Gasoline,32,8-Speed Automatic,Pursuit,SUV,4,DB Black Crystal Clearcoat,Black,All-wheel Drive\r\n804,2024 Ford Edge SEL,Ford,Edge,2024,"t 2L I-4 gasoline direct injection, DOHC, variable valve",4,Gasoline,10,Automatic,SEL,SUV,4,Carbonized Gray Metallic,Dune,All-wheel Drive\r\n805,2024 Chevrolet Equinox FWD RS,Chevrolet,Equinox,2024,"4 gasoline direct injection, DOHC, variable valve control",4,Gasoline,2,6-Speed Automatic Electronic with Overdrive,FWD RS,SUV,4,Summit White,Jet Black With Red Accents,Front-wheel Drive\r\n806,2024 Hyundai Tucson Hybrid N Line,Hyundai,Tucson Hybrid,2024,"ream 1.6L I-4 gasoline direct injection, DOHC, CVVD varia",4,Hybrid,10,Automatic,N Line,SUV,4,Titan Gray,Black w/Red Accents,All-wheel Drive\r\n807,2024 Jeep Wagoneer Base,Jeep,Wagoneer,2024,24V GDI DOHC Twin Turbo,6,Gasoline,20,8-Speed Automatic,Base,SUV,4,Diamond Black,Black,Four-wheel Drive\r\n808,2024 Land Rover Discovery Sport Dynamic SE,Land Rover,Discovery Sport,2024,16V GDI DOHC Turbo,4,Gasoline,19,9-Speed Automatic,Dynamic SE,SUV,4,Eiger Grey,Gray,All-wheel Drive\r\n809,2024 Hyundai Santa Cruz 2.5T Limited,Hyundai,Santa Cruz,2024,16V PDI DOHC Turbo,4,Gasoline,1,8-Speed Automatic with Auto-Shift,2.5T Limited,Pickup Truck,4,Phantom Black,Black,All-wheel Drive\r\n810,2023 Dodge Durango Pursuit,Dodge,Durango,2023,16V MPFI OHV,8,Gasoline,34,8-Speed Automatic,Pursuit,SUV,4,DB Black Crystal Clearcoat,Black,All-wheel Drive\r\n811,2023 Buick Envision Preferred,Buick,Envision,2023,16V GDI DOHC Turbo,4,Gasoline,6,9-Speed Automatic,Preferred,SUV,4,White Frost Tri-Coat,Ebony,All-wheel Drive\r\n812,2024 Dodge Hornet GT,Dodge,Hornet,2024,16V GDI DOHC Turbo,4,Gasoline,54,9-Speed Automatic,GT,SUV,4,Gray,Black,All-wheel Drive\r\n813,2024 Hyundai Santa Cruz 2.5T Limited,Hyundai,Santa Cruz,2024,16V PDI DOHC Turbo,4,Gasoline,1,8-Speed Automatic with Auto-Shift,2.5T Limited,Pickup Truck,4,Atlas,Dark Gray,All-wheel Drive\r\n814,2024 Mazda CX-90 PHEV Premium,Mazda,CX-90 PHEV,2024,16V GDI DOHC Hybrid,4,Hybrid,0,8-Speed Automatic,Premium,SUV,4,Artisan Red Metallic,Black,All-wheel Drive\r\n815,2024 Nissan Pathfinder SL 4WD,Nissan,Pathfinder,2024,"6 gasoline direct injection, DOHC, variable valve control",6,Gasoline,6,Automatic,SL 4WD,SUV,4,Deep Ocean Blue Pearl,Charcoal,Four-wheel Drive\r\n816,2024 Hyundai Tucson Hybrid SEL Convenience,Hyundai,Tucson Hybrid,2024,16V GDI DOHC Turbo Hybrid,4,Hybrid,10,6-Speed Automatic,SEL Convenience,SUV,4,Black Pearl,Black,All-wheel Drive\r\n817,2024 Ford Escape Active,Ford,Escape,2024,der,3,Gasoline,0,8-Speed Shiftable Automatic,Active,SUV,4,Iconic Silver,Ebony,Front-wheel Drive\r\n818,2024 Volkswagen Taos 1.5T SE,Volkswagen,Taos,2024,"4 gasoline direct injection, DOHC, variable valve control",4,Gasoline,11,8-speed automatic,1.5T SE,SUV,4,Pure White,Black,Front-wheel Drive\r\n819,2024 Honda CR-V Hybrid Sport,Honda,CR-V Hybrid,2024,16V GDI DOHC Hybrid,4,Hybrid,1,Automatic CVT,Sport,SUV,4,Lunar Silver Metallic,Black,All-wheel Drive\r\n820,2024 Volvo S60 Recharge Plug-In Hybrid T8 Plus Dark Theme,Volvo,S60 Recharge Plug-In Hybrid,2024,16V GDI DOHC Turbo Hybrid,4,Hybrid,3,8-Speed Automatic,T8 Plus Dark Theme,Sedan,4,Onyx Black Metallic,Charcoal,All-wheel Drive\r\n821,2024 Jeep Compass Latitude,Jeep,Compass,2024,16V GDI DOHC Turbo,4,Gasoline,0,8-Speed Automatic,Latitude,SUV,4,Bright White Clearcoat,Black,Four-wheel Drive\r\n822,2024 Ford Bronco Sport Big Bend,Ford,Bronco Sport,2024,"t 1.5L I-3 port/direct injection, DOHC, Ti-VCT variable v",3,Gasoline,13,Automatic,Big Bend,SUV,4,Carbonized Gray Metallic,Ebony,Four-wheel Drive\r\n823,2024 Ford Escape ST-Line,Ford,Escape,2024,der,4,Hybrid,0,CVT,ST-Line,SUV,4,Agate Black,Ebony W/Red Stitching,Front-wheel Drive\r\n824,2024 Chevrolet Silverado 1500 WT,Chevrolet,Silverado 1500,2024,16V GDI DOHC Turbo,4,Gasoline,2,Automatic,WT,Pickup Truck,4,Black,Jet Black,Four-wheel Drive\r\n825,2024 Chevrolet Equinox RS,Chevrolet,Equinox,2024,16V GDI DOHC Turbo,4,Gasoline,0,6-Speed Automatic,RS,SUV,4,Mosaic Black Metallic,Jet Black,Front-wheel Drive\r\n826,2024 Nissan Rogue SV,Nissan,Rogue,2024,"o 1.5L I-3 gasoline direct injection, DOHC, CVTCS variabl",3,Gasoline,4,Automatic,SV,SUV,4,Deep Ocean Blue Pearl,Charcoal,All-wheel Drive\r\n827,2024 Toyota Tundra Hybrid 1794 Edition,Toyota,Tundra Hybrid,2024,24V PDI DOHC Twin Turbo Hybrid,6,Hybrid,7,10-Speed Automatic,1794 Edition,Pickup Truck,4,Smoked Mesquite,Tan,Four-wheel Drive\r\n828,2023 Dodge Charger SXT,Dodge,Charger,2023,24V MPFI DOHC,6,Gasoline,15,8-Speed Automatic,SXT,Sedan,4,Blue,Black,Rear-wheel Drive\r\n829,2024 Hyundai Kona SEL,Hyundai,Kona,2024,16V MPFI DOHC,4,Gasoline,11,Automatic CVT,SEL,SUV,4,Mirage,Gray,Front-wheel Drive\r\n830,2024 Mazda CX-90 PHEV Base,Mazda,CX-90 PHEV,2024,"TIV-G 2.5L I-4 gasoline direct injection, DOHC, variable",4,Gasoline,5,8-Speed Automatic,Base,SUV,4,Deep Crystal Blue Mica,White,All-wheel Drive\r\n831,2024 Nissan Versa S,Nissan,Versa,2024,16V MPFI DOHC,4,Gasoline,4,Automatic CVT,S,Sedan,4,Gun Metallic,Charcoal,Front-wheel Drive\r\n832,2024 Hyundai Kona Limited,Hyundai,Kona,2024,16V GDI DOHC Turbo,4,Gasoline,15,8-Speed Automatic,Limited,SUV,4,Abyss Black Pearl,Black,Front-wheel Drive\r\n833,2024 RAM 3500 Big Horn,RAM,3500,2024,24V DDI OHV Turbo Diesel,6,Diesel,6,6-Speed Automatic,Big Horn,Pickup Truck,4,Diamond Black,Black,Four-wheel Drive\r\n834,2024 Hyundai Santa Cruz 2.5T NIGHT,Hyundai,Santa Cruz,2024,16V PDI DOHC Turbo,4,Gasoline,1,8-Speed Automatic with Auto-Shift,2.5T NIGHT,Pickup Truck,4,Hampton Gray,Black,All-wheel Drive\r\n835,2024 Hyundai Tucson Hybrid N Line,Hyundai,Tucson Hybrid,2024,"ream 1.6L I-4 gasoline direct injection, DOHC, CVVD varia",4,Hybrid,12,Automatic,N Line,SUV,4,Black Pearl,Black w/Red Accents,All-wheel Drive\r\n836,2024 Dodge Hornet GT AWD,Dodge,Hornet,2024,"ne 2L I-4 gasoline direct injection, DOHC, variable valve",4,Gasoline,10,Automatic,GT AWD,SUV,4,8 Ball,Black,All-wheel Drive\r\n837,2024 Hyundai Tucson Hybrid SEL Convenience,Hyundai,Tucson Hybrid,2024,16V GDI DOHC Turbo Hybrid,4,Hybrid,241,6-Speed Automatic,SEL Convenience,SUV,4,Shimmering Silver,Gray,All-wheel Drive\r\n838,2024 Jeep Compass Latitude,Jeep,Compass,2024,16V GDI DOHC Turbo,4,Gasoline,7,8-Speed Automatic,Latitude,SUV,4,Bright White Clearcoat,Black,Four-wheel Drive\r\n839,2023 Dodge Durango Pursuit,Dodge,Durango,2023,16V MPFI OHV,8,Gasoline,32,8-Speed Automatic,Pursuit,SUV,4,DB Black Crystal Clearcoat,Black,All-wheel Drive\r\n840,2024 GMC Sierra 1500 Denali Ultimate,GMC,Sierra 1500,2024,16V GDI OHV,8,Gasoline,12,10-Speed Automatic,Denali Ultimate,Pickup Truck,4,White Frost Tri-Coat,Alpine Umber,Four-wheel Drive\r\n841,2024 RAM 3500 Big Horn,RAM,3500,2024,24V DDI OHV Turbo Diesel,6,Diesel,21,6-Speed Automatic,Big Horn,Pickup Truck,4,Bright White Clearcoat,Black,Four-wheel Drive\r\n842,2024 Jeep Grand Cherokee Limited,Jeep,Grand Cherokee,2024,24V MPFI DOHC,6,Gasoline,6,8-Speed Automatic,Limited,SUV,4,Bright White Clearcoat,Global Black,Four-wheel Drive\r\n843,2024 Jeep Grand Cherokee Altitude,Jeep,Grand Cherokee,2024,"ar 3.6L V-6 DOHC, variable valve control, regular unleade",6,Gasoline,20,Automatic,Altitude,SUV,4,Silver Zynith,Global Black,Four-wheel Drive\r\n844,2024 BMW X7 xDrive40i,BMW,X7,2024,24V GDI DOHC Turbo,6,Gasoline,9,8-Speed Automatic,xDrive40i,SUV,4,Sparkling,Black,All-wheel Drive\r\n845,2024 RAM 3500 Tradesman,RAM,3500,2024,24V DDI OHV Turbo Diesel,6,Diesel,0,6-Speed Automatic,Tradesman,Pickup Truck,4,Bright White Clearcoat,Black / Diesel Gray,Four-wheel Drive\r\n846,2024 Hyundai Santa Cruz 2.5T NIGHT,Hyundai,Santa Cruz,2024,16V PDI DOHC Turbo,4,Gasoline,1,8-Speed Automatic with Auto-Shift,2.5T NIGHT,Pickup Truck,4,Phantom Black,Black,All-wheel Drive\r\n847,2024 Dodge Hornet GT AWD,Dodge,Hornet,2024,"ne 2L I-4 gasoline direct injection, DOHC, variable valve",4,Gasoline,24,Automatic,GT AWD,SUV,4,Acapulco Gold,Black,All-wheel Drive\r\n848,2024 Mazda CX-90 PHEV Base,Mazda,CX-90 PHEV,2024,"TIV-G 2.5L I-4 gasoline direct injection, DOHC, variable",4,Gasoline,5,Automatic,Base,SUV,4,Artisan Red Premium,Black,All-wheel Drive\r\n849,2024 Chevrolet Equinox LS,Chevrolet,Equinox,2024,"4 gasoline direct injection, DOHC, variable valve control",4,Gasoline,8,6-Speed Automatic Electronic with Overdrive,LS,SUV,4,Summit White,Medium Ash Gray,Front-wheel Drive\r\n850,2024 Jeep Wrangler 4xe Rubicon,Jeep,Wrangler 4xe,2024,16V GDI DOHC Turbo Hybrid,4,Hybrid,26,8-Speed Automatic,Rubicon,SUV,4,Hydro Blue Pearlcoat,Black,Four-wheel Drive\r\n851,2024 Jeep Grand Cherokee L Altitude,Jeep,Grand Cherokee L,2024,"ar 3.6L V-6 DOHC, variable valve control, regular unleade",6,Gasoline,175,Automatic,Altitude,SUV,4,Velvet Red Pearlcoat,Global Black,Four-wheel Drive\r\n852,2024 Jeep Wrangler 4xe Rubicon,Jeep,Wrangler 4xe,2024,16V GDI DOHC Turbo Hybrid,4,Hybrid,12,8-Speed Automatic,Rubicon,SUV,4,Bright White Clearcoat,Black,Four-wheel Drive\r\n853,2023 Jeep Wagoneer L Base,Jeep,Wagoneer L,2023,24V GDI DOHC Twin Turbo,6,Gasoline,20,8-Speed Automatic,Base,SUV,4,Diamond Black,Global Black,Four-wheel Drive\r\n854,2024 Nissan Frontier SV,Nissan,Frontier,2024,24V GDI DOHC,6,Gasoline,9,9-Speed Automatic,SV,Pickup Truck,4,Glacier White,Charcoal,Rear-wheel Drive\r\n855,2024 Ford Transit-250 Base,Ford,Transit-250,2024,"6 port/direct injection, DOHC, variable valve control, re",6,Gasoline,1,Automatic,Base,Cargo Van,3,Oxford White,Dk Palazzo Gry Fron,Rear-wheel Drive\r\n856,2024 Ford Edge ST-Line,Ford,Edge,2024,16V GDI DOHC Turbo,4,Gasoline,2,8-Speed Automatic,ST-Line,SUV,4,Black,Ebony,All-wheel Drive\r\n857,2024 Jeep Grand Cherokee 4xe 4x4,Jeep,Grand Cherokee 4xe,2024,"gasoline direct injection, DOHC, intercooled turbo, premi",4,Gasoline,3,Automatic,4x4,SUV,4,Midnight Sky,Global Black,Four-wheel Drive\r\n858,2024 Hyundai Santa Cruz 2.5L SEL,Hyundai,Santa Cruz,2024,16V PDI DOHC,4,Gasoline,1,8-Speed Automatic,2.5L SEL,Pickup Truck,4,Atlas,Black,All-wheel Drive\r\n859,2023 Jeep Grand Cherokee Laredo,Jeep,Grand Cherokee,2023,"ar 3.6L V-6 DOHC, variable valve control, regular unleade",6,Gasoline,16,8-speed automatic,Laredo,SUV,4,Silver Zynith,Global Black,Four-wheel Drive\r\n860,2024 Honda Odyssey Touring,Honda,Odyssey,2024,"6 gasoline direct injection, i-VTEC variable valve contro",6,Gasoline,0,Automatic,Touring,Passenger Van,4,Platinum White Pearl,Black,Front-wheel Drive\r\n861,2024 RAM 3500 Laramie Crew Cab 4x4 8\' Box,RAM,3500,2024,"6.7L I-6 diesel direct injection, VVT intercooled turbo,",6,Diesel,6,Automatic,Laramie Crew Cab 4x4 8&#39; Box,Pickup Truck,4,Red,Black,Four-wheel Drive\r\n862,2024 RAM 3500 Big Horn,RAM,3500,2024,24V DDI OHV Turbo Diesel,6,Diesel,6,6-Speed Automatic,Big Horn,Pickup Truck,4,Bright White Clearcoat,Black,Four-wheel Drive\r\n863,2024 Hyundai Tucson Hybrid SEL Convenience,Hyundai,Tucson Hybrid,2024,"ream 1.6L I-4 gasoline direct injection, DOHC, CVVD varia",4,Hybrid,1,6-Speed Automatic,SEL Convenience,SUV,4,Black Pearl,Black,All-wheel Drive\r\n864,2024 Jeep Grand Cherokee Laredo,Jeep,Grand Cherokee,2024,OHV,6,Gasoline,1,8-Speed Automatic,Laredo,SUV,4,Bright White Clearcoat,Global Black,Four-wheel Drive\r\n865,2024 Volkswagen Jetta 1.4T S,Volkswagen,Jetta,2024,"4 gasoline direct injection, DOHC, variable valve control",4,Gasoline,7,8-Speed Automatic with Tiptronic,1.4T S,Sedan,4,Pure White,Titan Black,Front-wheel Drive\r\n866,2024 RAM 2500 Laramie,RAM,2500,2024,24V DDI OHV Turbo Diesel,6,Diesel,17,6-Speed Automatic,Laramie,Pickup Truck,4,Pearl White,Black,Four-wheel Drive\r\n867,2024 Ford Explorer XLT,Ford,Explorer,2024,16V GDI DOHC Turbo,4,Gasoline,2500,10-Speed Automatic,XLT,SUV,4,Star White,Sandstone,Rear-wheel Drive\r\n868,2024 Kia Sportage SX,Kia,Sportage,2024,16V PDI DOHC,4,Gasoline,1,8-Speed Automatic,SX,SUV,4,White,Black,Front-wheel Drive\r\n869,2024 Nissan Sentra SV,Nissan,Sentra,2024,"gasoline direct injection, DOHC, variable valve control,",4,Gasoline,4,Automatic,SV,Sedan,4,Gun Metallic,Charcoal,Front-wheel Drive\r\n870,2024 Nissan Titan SV,Nissan,Titan,2024,"ce 5.6L V-8 gasoline direct injection, DOHC, variable val",8,Gasoline,10,Automatic,SV,Pickup Truck,4,Super Black,Black,Four-wheel Drive\r\n871,2023 Dodge Durango Pursuit,Dodge,Durango,2023,24V MPFI DOHC,6,Gasoline,35,8-Speed Automatic,Pursuit,SUV,4,White Knuckle Clearcoat,Black,All-wheel Drive\r\n872,2024 Volkswagen Jetta 1.4T S,Volkswagen,Jetta,2024,"4 gasoline direct injection, DOHC, variable valve control",4,Gasoline,6,8-Speed Automatic with Tiptronic,1.4T S,Sedan,4,Pure White,Titan Black,Front-wheel Drive\r\n873,2024 Chevrolet Silverado 1500 Custom Trail Boss,Chevrolet,Silverado 1500,2024,"5.3L V-8 gasoline direct injection, variable valve contr",8,Gasoline,5,Automatic,Custom Trail Boss,Pickup Truck,4,Summit White,Jet Black,Four-wheel Drive\r\n874,2024 Dodge Hornet GT AWD,Dodge,Hornet,2024,"ne 2L I-4 gasoline direct injection, DOHC, variable valve",4,Gasoline,4440,9-speed automatic,GT AWD,SUV,4,Acapulco Gold,Black,All-wheel Drive\r\n875,2024 Jeep Compass Limited,Jeep,Compass,2024,16V GDI DOHC Turbo,4,Gasoline,10,8-Speed Automatic,Limited,SUV,4,Sting Gray Clearcoat,Black,Four-wheel Drive\r\n876,2024 GMC Sierra 2500 Pro,GMC,Sierra 2500,2024,16V GDI OHV,8,Gasoline,3,10-Speed Automatic,Pro,Pickup Truck,2,Summit White,Jet Black,Rear-wheel Drive\r\n877,2024 Mazda CX-90 PHEV Premium Plus,Mazda,CX-90 PHEV,2024,DOHC 16V LEV3-SULEV30,4,PHEV Hybrid Fuel,26,Automatic,Premium Plus,SUV,4,Artisan Red Premium,Black,All-wheel Drive\r\n878,2023 Dodge Durango Pursuit,Dodge,Durango,2023,16V MPFI OHV,8,Gasoline,33,8-Speed Automatic,Pursuit,SUV,4,DB Black Crystal Clearcoat,Black,All-wheel Drive\r\n879,2024 Jeep Grand Cherokee 4xe 4x4,Jeep,Grand Cherokee 4xe,2024,"gasoline direct injection, DOHC, intercooled turbo, premi",4,Gasoline,3,Automatic,4x4,SUV,4,Diamond Black Crystal Pearlcoat,Global Black,Four-wheel Drive\r\n880,2023 Dodge Durango Pursuit,Dodge,Durango,2023,16V MPFI OHV,8,Gasoline,32,8-Speed Automatic,Pursuit,SUV,4,DB Black Crystal Clearcoat,Black,All-wheel Drive\r\n881,2024 Jeep Compass Latitude,Jeep,Compass,2024,16V GDI DOHC Turbo,4,Gasoline,7,8-Speed Automatic,Latitude,SUV,4,Metallic,Black,Four-wheel Drive\r\n882,2024 Ford Escape Active,Ford,Escape,2024,"t 1.5L I-3 port/direct injection, DOHC, Ti-VCT variable v",3,Gasoline,2,8-Speed Automatic,Active,SUV,4,Carbonized Gray Metallic,Ebony Black,Front-wheel Drive\r\n883,2024 RAM 3500 Laramie,RAM,3500,2024,oled Turbo Diesel I-6 6.7 L/408,6,Diesel,49,Automatic,Laramie,Pickup Truck,4,Billet Silver Metallic Clearcoat,Black,Four-wheel Drive\r\n884,2024 BMW 740 i,BMW,740,2024,24V GDI DOHC Turbo,6,Gasoline,19,8-Speed Automatic,i,Sedan,4,Black Sapphire Metallic,Black,Rear-wheel Drive\r\n885,2024 Hyundai Palisade SEL,Hyundai,Palisade,2024,24V GDI DOHC,6,Gasoline,25,8-Speed Automatic,SEL,SUV,4,Steel / Graphite,Gray / Black,All-wheel Drive\r\n886,2024 GMC Terrain Denali,GMC,Terrain,2024,16V GDI DOHC Turbo,4,Gasoline,0,9-Speed Automatic,Denali,SUV,4,White Frost Tri-Coat,Light Platinum,All-wheel Drive\r\n887,2024 Hyundai Tucson Hybrid Limited,Hyundai,Tucson Hybrid,2024,"ream 1.6L I-4 gasoline direct injection, DOHC, CVVD varia",4,Hybrid,16,Automatic,Limited,SUV,4,Amazon Gray,Black,All-wheel Drive\r\n888,2024 Ford Edge Titanium,Ford,Edge,2024,"t 2L I-4 gasoline direct injection, DOHC, variable valve",4,Gasoline,4723,8-Speed Automatic,Titanium,SUV,4,Agate Black Metallic,Ebony,All-wheel Drive\r\n889,2024 Chevrolet Silverado 1500 ZR2,Chevrolet,Silverado 1500,2024,16V GDI OHV,8,Gasoline,2,10-Speed Automatic,ZR2,Pickup Truck,4,Summit White,Gray,Four-wheel Drive\r\n890,2024 Dodge Hornet R/T Plus,Dodge,Hornet,2024,16V GDI DOHC Turbo Hybrid,4,Hybrid,5,6-Speed Automatic,R/T Plus,SUV,4,Gray,Black,All-wheel Drive\r\n891,2024 Subaru Legacy Premium,Subaru,Legacy,2024,16V GDI DOHC,4,Gasoline,5,Automatic CVT,Premium,Sedan,4,Ice Silver Metallic,Gray,All-wheel Drive\r\n892,2024 Jeep Grand Wagoneer Series III,Jeep,Grand Wagoneer,2024,24V GDI DOHC Twin Turbo,6,Gasoline,0,8-Speed Automatic,Series III,SUV,4,Midnight Sky,Global Black,Four-wheel Drive\r\n893,2024 Chevrolet Silverado 1500 LT,Chevrolet,Silverado 1500,2024,16V GDI OHV,8,Gasoline,17,Automatic,LT,Pickup Truck,4,Black,Jet Black,Four-wheel Drive\r\n894,2024 Volkswagen Atlas 2.0T Peak Edition SE w/Technology,Volkswagen,Atlas,2024,16V GDI DOHC Turbo,4,Gasoline,0,8-Speed Automatic,2.0T Peak Edition SE w/Technology,SUV,4,Avocado Green,Titan Black,All-wheel Drive\r\n895,2024 Subaru Impreza RS,Subaru,Impreza,2024,16V GDI DOHC,4,Gasoline,5,Automatic CVT,RS,Hatchback,4,Crystal Black Silica,Black,All-wheel Drive\r\n896,2024 RAM 2500 Tradesman 4x4 Crew Cab 8 Box,RAM,2500,2024,"6.7L I-6 diesel direct injection, VVT intercooled turbo,",6,Diesel,15,6-Speed A/T,Tradesman 4x4 Crew Cab 8 Box,Pickup Truck,4,Bright White Clearcoat,Diesel Gray/Black,Four-wheel Drive\r\n897,2024 RAM 3500 Tradesman Crew Cab 4x4 8\' Box,RAM,3500,2024,"High Output 6.7L I-6 diesel direct injection, VVT interc",6,Diesel,6,Automatic,Tradesman Crew Cab 4x4 8&#39; Box,Pickup Truck,4,Granite Crystal Metallic Clearcoat,Black Interior Color,Four-wheel Drive\r\n898,2024 Ford Bronco Sport Outer Banks,Ford,Bronco Sport,2024,oBoost,3,Gasoline,0,8-Speed Automatic,Outer Banks,SUV,4,Shadow Black,Ebony/Roast,Four-wheel Drive\r\n899,2024 Jeep Wagoneer L Series II,Jeep,Wagoneer L,2024,24V GDI DOHC Twin Turbo,6,Gasoline,16,8-Speed Automatic,Series II,SUV,4,Riverrock Green,Global Black,Four-wheel Drive\r\n900,2024 Jeep Compass Latitude,Jeep,Compass,2024,16V GDI DOHC Turbo,4,Gasoline,7,8-Speed Automatic,Latitude,SUV,4,Bright White Clearcoat,Black,Four-wheel Drive\r\n901,2023 Dodge Durango Pursuit,Dodge,Durango,2023,16V MPFI OHV,8,Gasoline,11,8-Speed Automatic,Pursuit,SUV,4,DB Black Crystal Clearcoat,Black,All-wheel Drive\r\n902,2024 GMC Sierra 2500 Pro,GMC,Sierra 2500,2024,16V GDI OHV,8,Gasoline,0,10-Speed Automatic,Pro,Pickup Truck,2,Summit White,Jet Black,Rear-wheel Drive\r\n903,2024 Volkswagen Taos 1.5T SE,Volkswagen,Taos,2024,"4 gasoline direct injection, DOHC, variable valve control",4,Gasoline,11,8-speed automatic,1.5T SE,SUV,4,Deep Black Pearl,Black,Front-wheel Drive\r\n904,2024 Volkswagen Taos 1.5T S,Volkswagen,Taos,2024,16V GDI DOHC Turbo,4,Gasoline,5,7-Speed DSGA? Automatic w/ 4MO,1.5T S,SUV,4,Pyrite Silver Metallic,Black,All-wheel Drive\r\n905,2024 Hyundai Tucson Hybrid N Line,Hyundai,Tucson Hybrid,2024,16V GDI DOHC Turbo Hybrid,4,Hybrid,15,6-Speed Automatic,N Line,SUV,4,Black Pearl,Black,All-wheel Drive\r\n906,2024 Mazda CX-90 PHEV Base,Mazda,CX-90 PHEV,2024,"TIV-G 2.5L I-4 gasoline direct injection, DOHC, variable",4,Gasoline,2,8-Speed Automatic,Base,SUV,4,Deep Crystal Blue Mica,Black,All-wheel Drive\r\n907,2024 RAM 2500 Tradesman,RAM,2500,2024,16V MPFI OHV,8,Gasoline,5,8-Speed Automatic,Tradesman,Pickup Truck,4,Bright White Clearcoat,Black,Four-wheel Drive\r\n908,2024 RAM 3500 Laramie,RAM,3500,2024,24V DDI OHV Turbo Diesel,6,Diesel,6,6-Speed Automatic,Laramie,Pickup Truck,4,Pearl White,Black,Four-wheel Drive\r\n909,2024 Hyundai Elantra HEV Blue,Hyundai,Elantra HEV,2024,16V GDI DOHC Hybrid,4,Hybrid,15,6-Speed DCT Automatic,Blue,Sedan,4,Gray Pearl,Black,Front-wheel Drive\r\n910,2024 Volkswagen Jetta 1.5T SEL,Volkswagen,Jetta,2024,16V GDI DOHC Turbo,4,Gasoline,28,8-Speed Automatic,1.5T SEL,Sedan,4,Opal White Pearl Effect,Volcano Brown,Front-wheel Drive\r\n911,2024 Mazda CX-90 PHEV Premium Plus,Mazda,CX-90 PHEV,2024,DOHC 16V LEV3-SULEV30,4,PHEV Hybrid Fuel,4,Automatic,Premium Plus,SUV,4,Jet Black Mica,Black,All-wheel Drive\r\n912,2024 Kia Sportage S,Kia,Sportage,2024,"4 port/direct injection, DOHC, CVVT variable valve contro",4,Gasoline,0,8-Speed Automatic,S,SUV,4,White Pearl,Black,All-wheel Drive\r\n913,2024 Jeep Wagoneer Base,Jeep,Wagoneer,2024,24V GDI DOHC Twin Turbo,6,Gasoline,5,8-Speed Automatic,Base,SUV,4,Diamond Black,Black,

In [2]:
!ls

 sample_data		 'test_data (2).csv'	   'train_data (2).csv'
'test_data (2) (1).csv'  'train_data (2) (1).csv'

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
train_df = pd.read_csv('train_data (2).csv')
test_df = pd.read_csv('test_data (2).csv')

In [6]:
train_df.head()

,id,name,make,model,year,price,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain
0,1,2024 INFINITI QX50 SPORT,INFINITI,QX50,2024,49404.0,ER,4.0,Gasoline,7.0,(CVT) CONT VAR.,SPORT,NaN,4.0,Radiant White,Monaco Red,Front-wheel Drive
1,2,2024 Mazda CX-90 PHEV Base,Mazda,CX-90 PHEV,2024,55399.0,"TIV-G 2.5L I-4 gasoline direct injection, DOHC...",4.0,Gasoline,2.0,8-Speed Automatic,Base,SUV,4.0,Soul Red Crystal Metallic,Griege,All-wheel Drive
2,3,2024 Honda CR-V Hybrid Sport Touring,Honda,CR-V Hybrid,2024,42005.0,16V GDI DOHC Hybrid,4.0,Hybrid,1.0,Automatic CVT,Sport Touring,SUV,4.0,Radiant Red Metallic,Black,All-wheel Drive
3,4,2024 Jeep Grand Cherokee L Limited,Jeep,Grand Cherokee L,2024,52567.0,OHV,6.0,Gasoline,246.0,8-Speed Automatic,Limited,SUV,4.0,Velvet Red Pearlcoat,Global Black,Four-wheel Drive
4,5,2024 Acura MDX Technology,Acura,MDX,2024,56800.0,24V GDI SOHC,6.0,Gasoline,5.0,10-Speed Automatic,Technology,SUV,4.0,Gray,NaN,Front-wheel Drive

In [5]:
# Subtask 1
train_df.groupby(by='cylinders')['price'].mean()

cylinders
0.0    66045.000000
3.0    32673.421053
4.0    41099.911051
6.0    60456.972973
8.0    58899.587302
Name: price, dtype: float64

In [6]:
subtask_1 = pd.DataFrame({
    'subtaskID': [1],
    'datapointID': [1],
    'answer': train_df.groupby(by='cylinders')['price'].mean()[0],
})
subtask_1.head()

   subtaskID  datapointID   answer
0          1            1  66045.0

In [29]:
train_df.head()

,id,name,make,model,year,price,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain
0,1,2024 INFINITI QX50 SPORT,INFINITI,QX50,2024,49404.0,ER,4.0,Gasoline,7.0,(CVT) CONT VAR.,SPORT,NaN,4.0,Radiant White,Monaco Red,Front-wheel Drive
1,2,2024 Mazda CX-90 PHEV Base,Mazda,CX-90 PHEV,2024,55399.0,"TIV-G 2.5L I-4 gasoline direct injection, DOHC...",4.0,Gasoline,2.0,8-Speed Automatic,Base,SUV,4.0,Soul Red Crystal Metallic,Griege,All-wheel Drive
2,3,2024 Honda CR-V Hybrid Sport Touring,Honda,CR-V Hybrid,2024,42005.0,16V GDI DOHC Hybrid,4.0,Hybrid,1.0,Automatic CVT,Sport Touring,SUV,4.0,Radiant Red Metallic,Black,All-wheel Drive
3,4,2024 Jeep Grand Cherokee L Limited,Jeep,Grand Cherokee L,2024,52567.0,OHV,6.0,Gasoline,246.0,8-Speed Automatic,Limited,SUV,4.0,Velvet Red Pearlcoat,Global Black,Four-wheel Drive
4,5,2024 Acura MDX Technology,Acura,MDX,2024,56800.0,24V GDI SOHC,6.0,Gasoline,5.0,10-Speed Automatic,Technology,SUV,4.0,Gray,NaN,Front-wheel Drive

In [34]:
# Subtask 2 - regression model to predict the `price` for all cars in `test_data.csv`
from xgboost import XGBRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

train_df = train_df.dropna(subset=['price'])

X_train = train_df.drop(columns=['id', 'price'])
y_train = train_df['price']

X_test = test_df.drop(columns=['id'])

cat_cols = X_train.select_dtypes(exclude='number').columns
num_cols = X_train.select_dtypes(include='number').columns

trans = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ],
    remainder='passthrough'
)

pipe = Pipeline([
    ('trans', trans),
    ('regressor', XGBRegressor(n_estimators=250, n_jobs=-1, random_state=42, missing=np.nan, device='cuda'),)
], verbose=True)

pipe.fit(X_train, y_train)

[Pipeline] ............. (step 1 of 2) Processing trans, total=   0.0s

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [18:14:37] WARNING: /__w/xgboost/xgboost/src/context.cc:55: No visible GPU is found, setting device to CPU.
  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [18:14:37] WARNING: /__w/xgboost/xgboost/src/context.cc:218: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  bst.update(dtrain, iteration=i, fobj=obj)

[Pipeline] ......... (step 2 of 2) Processing regressor, total=   0.4s

/usr/local/lib/python3.13/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('trans',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['name', 'make', 'model', 'engine', 'fuel', 'transmission', 'trim',
       'body', 'drivetrain'],
      dtype='object'))])),
                ('regressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=No...
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=250, n_jobs=-1,
                              num_parallel_tree=None, ...))],
         verbose=True)

In [40]:
# Subtask 2/Alt (with TargetEncoder) - regression model to predict the `price` for all cars in `test_data.csv`
from xgboost import XGBRegressor
from sklearn.preprocessing import TargetEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

train_df = train_df.dropna(subset=['price'])

X_train = train_df.drop(columns=['id', 'price'])
y_train = train_df['price']

X_test = test_df.drop(columns=['id'])

# We define the columns with high cardinality (many unique text values)
high_card_cols = ['name', 'make', 'model', 'fuel', 'engine', 'transmission', 'trim', 'body', 'exterior_color', 'interior_color', 'drivetrain']
num_cols = ['year', 'cylinders', 'mileage', 'doors']

preprocessor = ColumnTransformer(
    transformers=[
        ('target', TargetEncoder(smooth='auto', random_state=42), high_card_cols)
    ],
    remainder='passthrough'
)

pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(n_estimators=500, n_jobs=-1, random_state=42, missing=np.nan, device='cuda'),)
], verbose=True)

pipe.fit(X_train, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

[Pipeline] ...... (step 1 of 2) Processing preprocessor, total=   1.8s

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [18:21:53] WARNING: /__w/xgboost/xgboost/src/context.cc:55: No visible GPU is found, setting device to CPU.
  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [18:21:53] WARNING: /__w/xgboost/xgboost/src/context.cc:218: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  bst.update(dtrain, iteration=i, fobj=obj)

[Pipeline] ......... (step 2 of 2) Processing regressor, total=  20.8s

/usr/local/lib/python3.13/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('target',
                                                  TargetEncoder(random_state=42),
                                                  ['name', 'make', 'model',
                                                   'fuel', 'engine',
                                                   'transmission', 'trim',
                                                   'body', 'exterior_color',
                                                   'interior_color',
                                                   'drivetrain'])])),
                ('regressor',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsampl...
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=500, n_jobs=-1,
                              num_parallel_tree=None, ...))],
         verbose=True)

In [41]:
y_preds = pipe.predict(X_test)

In [42]:
abs(y_preds.std() - train_df['price'].std()) # Seems pretty similar

np.float32(4143.46)

In [43]:
subtask_2 = pd.DataFrame({
    'subtaskID': 2,
    'datapointID': test_df['id'],
    'answer': y_preds,
})
subtask_2.head()

   subtaskID  datapointID        answer
0          2          803  46691.414062
1          2          804  39232.628906
2          2          805  31104.685547
3          2          806  37593.027344
4          2          807  67810.296875

In [44]:
submission = pd.concat([subtask_1, subtask_2])
submission.to_csv('submission.csv', index=False)

files.download('submission.csv')